name: Deploy

on:
  push:
    branches: [main]

jobs:
  ci:
    uses: wcmchenry3-stack/powerplayshistory_site/.github/workflows/ci.yml@main
    secrets: inherit

  deploy:
    needs: ci
    uses: wcmchenry3-stack/.github/.github/workflows/called-deploy-render.yml@main
    with:
      service-name: 'powerplayshistory-site'
      service-id: 'RENDER_SERVICE_ID_PLACEHOLDER'
      zap-target-url: 'https://powerplayshistory-site.onrender.com'
    secrets: inherit
